name: eeg-decoding
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  - matplotlib
  - scipy
  - pip:
    - moabb      
    - braindecode
    - ewtpy       
    - mne        
    - loguru
    - typer
    - tqdm
    - python-dotenv
    - -e .     